# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daadef62c0df129d3248ed92fe0def39abca809c1c8f911b19da0358f75546518099ca4fd1ecb779590aa274d1bd0340504c1407e179763f29704612691d16f9

test:
  secret_key_base: 38c92a683e29b2977dbbf7122ba79ba5a922a22f02eba8df5271ca8e3b06853c5c6ab63a808a528128ff38dbb5344e3695510b1b2c60c4fd68b84327d72e265f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
